var searchData=
[
  ['edges',['edges',['../class_polygon2d.html#a45b7428e12a193c12faab129670baddb',1,'Polygon2d']]],
  ['effect',['Effect',['../classgd_1_1_effect.html',1,'gd']]],
  ['effectmetadata',['EffectMetadata',['../classgd_1_1_effect_metadata.html',1,'gd::EffectMetadata'],['../classgd_1_1_effect_metadata.html#a4cfd4b2602398a61e23dc0a44c5b6e50',1,'gd::EffectMetadata::EffectMetadata(const gd::String &amp;type_)'],['../classgd_1_1_effect_metadata.html#ac59d020c796c3270e5fcdd72176497ab',1,'gd::EffectMetadata::EffectMetadata()']]],
  ['effectscodegenerator',['EffectsCodeGenerator',['../classgd_1_1_effects_code_generator.html',1,'gd']]],
  ['empty',['empty',['../classgd_1_1_object_groups_container.html#a583814ed26c049b863df5d7208f38853',1,'gd::ObjectGroupsContainer::empty()'],['../classgd_1_1_string.html#ac6f7ef4e6407b38687eb376bffe22143',1,'gd::String::empty()'],['../classgd_1_1_serializable_with_name_list.html#a955855a70e62ef456cf8bed6faffec11',1,'gd::SerializableWithNameList::empty()'],['../classgd_1_1_s_ptr_list.html#a5e0614fe4df98f4538c92fd19d51204d',1,'gd::SPtrList::empty()']]],
  ['emptyevent',['EmptyEvent',['../classgd_1_1_empty_event.html',1,'gd']]],
  ['emptynode',['EmptyNode',['../structgd_1_1_empty_node.html',1,'gd']]],
  ['emptyobjectslistneeded',['EmptyObjectsListNeeded',['../classgd_1_1_events_code_generation_context.html#a9db1fa58b644073fb26e4b132fb75430',1,'gd::EventsCodeGenerationContext']]],
  ['enableextensionloadinglogs',['EnableExtensionLoadingLogs',['../classgd_1_1_platform.html#aa3d93b847454b69632bda3ad351589fb',1,'gd::Platform']]],
  ['enableimagesunloading',['EnableImagesUnloading',['../classgd_1_1_image_manager.html#a6143e62ac3c27b17617a15baadb93a84',1,'gd::ImageManager']]],
  ['end',['end',['../classgd_1_1_string.html#ab3c24e4ebc0d5a1b7945346b3c099943',1,'gd::String::end()'],['../classgd_1_1_string.html#aa5ed3b36d31003ebb71627dec107f1e8',1,'gd::String::end() const']]],
  ['ensurebehavioreventsfunctionsproperparameters',['EnsureBehaviorEventsFunctionsProperParameters',['../classgd_1_1_whole_project_refactorer.html#a4fccc70cc67077fa5e77a310f1918129',1,'gd::WholeProjectRefactorer']]],
  ['entercustomcondition',['EnterCustomCondition',['../classgd_1_1_events_code_generation_context.html#a69469bf336a0e1219502c4aad00273fa',1,'gd::EventsCodeGenerationContext']]],
  ['erase',['erase',['../classgd_1_1_string.html#ad0b988e0d91a3d5321a5483495b4238e',1,'gd::String::erase(iterator first, iterator last)'],['../classgd_1_1_string.html#aec3a7ada7fa952ba4d96d4119d358b7d',1,'gd::String::erase(iterator p)'],['../classgd_1_1_string.html#a8bc6ea70f1f7cfe460d05248faa6dab1',1,'gd::String::erase(size_type pos=0, size_type len=npos)']]],
  ['erroroccurred',['errorOccurred',['../classgd_1_1_events_code_generator.html#ae078863765c6faa3a97f0ef72121460e',1,'gd::EventsCodeGenerator::errorOccurred()'],['../classgd_1_1_events_code_generator.html#ae4eea93213a65769dbd2b8d8f55d9d73',1,'gd::EventsCodeGenerator::ErrorOccurred() const']]],
  ['eventmetadata',['EventMetadata',['../classgd_1_1_event_metadata.html',1,'gd']]],
  ['events_20_28classes_20defining_20the_20event_20system_20and_20some_20tools_20associated_20with_20events_29',['Events (Classes defining the event system and some tools associated with events)',['../group___events.html',1,'']]],
  ['eventsbasedbehavior',['EventsBasedBehavior',['../classgd_1_1_events_based_behavior.html',1,'gd']]],
  ['eventscodegenerationcontext',['EventsCodeGenerationContext',['../classgd_1_1_events_code_generation_context.html',1,'gd::EventsCodeGenerationContext'],['../classgd_1_1_events_code_generation_context.html#a5e0d0237aa1040ee653df8fc31df84e2',1,'gd::EventsCodeGenerationContext::EventsCodeGenerationContext()']]],
  ['eventscodegenerator',['EventsCodeGenerator',['../classgd_1_1_events_code_generator.html',1,'gd::EventsCodeGenerator'],['../classgd_1_1_events_code_generator.html#a09dacfeeeff124e192e9b332c881de8e',1,'gd::EventsCodeGenerator::EventsCodeGenerator(gd::Project &amp;project_, const gd::Layout &amp;layout, const gd::Platform &amp;platform_)'],['../classgd_1_1_events_code_generator.html#a0d228409d68d86fe0f6a675ea8e0d3ba',1,'gd::EventsCodeGenerator::EventsCodeGenerator(const gd::Platform &amp;platform, gd::ObjectsContainer &amp;globalObjectsAndGroups_, const gd::ObjectsContainer &amp;objectsAndGroups_)']]],
  ['eventscodenamemangler',['EventsCodeNameMangler',['../class_events_code_name_mangler.html',1,'']]],
  ['eventscontext',['EventsContext',['../classgd_1_1_events_context.html',1,'gd']]],
  ['eventscontextanalyzer',['EventsContextAnalyzer',['../classgd_1_1_events_context_analyzer.html',1,'gd']]],
  ['eventsfunction',['EventsFunction',['../classgd_1_1_events_function.html',1,'gd']]],
  ['eventsfunctionscontainer',['EventsFunctionsContainer',['../classgd_1_1_events_functions_container.html',1,'gd']]],
  ['eventsfunctionsextension',['EventsFunctionsExtension',['../classgd_1_1_events_functions_extension.html',1,'gd']]],
  ['eventsfunctiontoobjectscontainer',['EventsFunctionToObjectsContainer',['../classgd_1_1_events_function_tools.html#a80250c29bce57c6d290941adb9f84a2a',1,'gd::EventsFunctionTools']]],
  ['eventsfunctiontools',['EventsFunctionTools',['../classgd_1_1_events_function_tools.html',1,'gd']]],
  ['eventslist',['EventsList',['../classgd_1_1_events_list.html',1,'gd']]],
  ['eventslistnextuniqueid',['eventsListNextUniqueId',['../classgd_1_1_events_code_generator.html#a93d7b4e5e142ab73165f9fe7c9e74d05',1,'gd::EventsCodeGenerator']]],
  ['eventslistserialization',['EventsListSerialization',['../classgd_1_1_events_list_serialization.html',1,'gd']]],
  ['eventslistunfolder',['EventsListUnfolder',['../class_events_list_unfolder.html',1,'']]],
  ['eventsparameterslister',['EventsParametersLister',['../classgd_1_1_events_parameters_lister.html',1,'gd']]],
  ['eventsrefactorer',['EventsRefactorer',['../classgd_1_1_events_refactorer.html',1,'gd']]],
  ['eventsremover',['EventsRemover',['../classgd_1_1_events_remover.html',1,'gd']]],
  ['eventssearchresult',['EventsSearchResult',['../classgd_1_1_events_search_result.html',1,'gd']]],
  ['eventstypeslister',['EventsTypesLister',['../classgd_1_1_events_types_lister.html',1,'gd']]],
  ['eventsvariablesfinder',['EventsVariablesFinder',['../classgd_1_1_events_variables_finder.html',1,'gd']]],
  ['exception',['exception',['../classutf8_1_1exception.html',1,'utf8']]],
  ['expandobjectsname',['ExpandObjectsName',['../classgd_1_1_events_code_generator.html#a75704cc7a8ea3159b99eea8e7be398bd',1,'gd::EventsCodeGenerator']]],
  ['exporteddependencyresolver',['ExportedDependencyResolver',['../classgd_1_1_exported_dependency_resolver.html',1,'gd']]],
  ['exposeactionsresources',['ExposeActionsResources',['../classgd_1_1_platform_extension.html#a8e46e6878e76ae6fa968f5a22137e820',1,'gd::PlatformExtension']]],
  ['exposeaudio',['ExposeAudio',['../classgd_1_1_arbitrary_resource_worker.html#a7e4de092a2a346ba1565f78289bf8be5',1,'gd::ArbitraryResourceWorker::ExposeAudio()'],['../classgd_1_1_resources_in_use_helper.html#a7545e51c72101ab9cd11c23fae7eeb3e',1,'gd::ResourcesInUseHelper::ExposeAudio()'],['../classgd_1_1_resources_renamer.html#a3f180c09b4cb744e889e07e6daa97202',1,'gd::ResourcesRenamer::ExposeAudio()']]],
  ['exposeconditionsresources',['ExposeConditionsResources',['../classgd_1_1_platform_extension.html#a9ee91447449f4f4ce45885dd2153a815',1,'gd::PlatformExtension']]],
  ['exposefile',['ExposeFile',['../classgd_1_1_arbitrary_resource_worker.html#abeed1c45b417ecdaeea04ac54bc9c5cb',1,'gd::ArbitraryResourceWorker::ExposeFile()'],['../classgd_1_1_resources_absolute_path_checker.html#a98a2a70c5c25a7a0273170eed45b60b7',1,'gd::ResourcesAbsolutePathChecker::ExposeFile()'],['../classgd_1_1_resources_in_use_helper.html#a0f704af18ea500372b689bc325415f5c',1,'gd::ResourcesInUseHelper::ExposeFile()'],['../classgd_1_1_resources_merging_helper.html#ad7a66958e2917febc12243bd6a12be92',1,'gd::ResourcesMergingHelper::ExposeFile()'],['../classgd_1_1_resources_renamer.html#af8f2a31acb309209f221329787a583e8',1,'gd::ResourcesRenamer::ExposeFile()']]],
  ['exposefont',['ExposeFont',['../classgd_1_1_arbitrary_resource_worker.html#a4343f0e1a80071fc2e1bb2e96f1a463f',1,'gd::ArbitraryResourceWorker::ExposeFont()'],['../classgd_1_1_resources_in_use_helper.html#a135b16964c3e69daef40c9ce8e1c1570',1,'gd::ResourcesInUseHelper::ExposeFont()'],['../classgd_1_1_resources_renamer.html#a83820966c18bb153ebc6d2c37caf61b1',1,'gd::ResourcesRenamer::ExposeFont()']]],
  ['exposeimage',['ExposeImage',['../classgd_1_1_arbitrary_resource_worker.html#a345f5c6dc952e194d925b1ec94baeca2',1,'gd::ArbitraryResourceWorker::ExposeImage()'],['../classgd_1_1_resources_in_use_helper.html#a05c87b10ddeec48acdd3fef22d1a4496',1,'gd::ResourcesInUseHelper::ExposeImage()'],['../classgd_1_1_resources_renamer.html#a9574923cfb29909f5084d8da8dcfaa7e',1,'gd::ResourcesRenamer::ExposeImage()']]],
  ['exposeprojectevents',['ExposeProjectEvents',['../classgd_1_1_whole_project_refactorer.html#a3d3ce9945c08b78e94e0d501ae86ce7f',1,'gd::WholeProjectRefactorer::ExposeProjectEvents(gd::Project &amp;project, gd::ArbitraryEventsWorker &amp;worker)'],['../classgd_1_1_whole_project_refactorer.html#a117f286fda78f23733b7d2ef85721722',1,'gd::WholeProjectRefactorer::ExposeProjectEvents(gd::Project &amp;project, gd::ArbitraryEventsWorkerWithContext &amp;worker)']]],
  ['exposeresources',['ExposeResources',['../classgd_1_1_sprite_object.html#a77a3957e1870c6e608798a08507de902',1,'gd::SpriteObject::ExposeResources()'],['../classgd_1_1_arbitrary_resource_worker.html#a7f46fa8187b8d834bc092bd4cd247fa4',1,'gd::ArbitraryResourceWorker::ExposeResources()'],['../classgd_1_1_object.html#ad02a158af2c102e394f63c4852636b93',1,'gd::Object::ExposeResources()'],['../classgd_1_1_project.html#a0eefaf0417c4848a5dfd0c08938b3624',1,'gd::Project::ExposeResources()']]],
  ['exposeshader',['ExposeShader',['../classgd_1_1_arbitrary_resource_worker.html#a285af1d18689e64c39b7a962d0a4fadd',1,'gd::ArbitraryResourceWorker']]],
  ['expression',['Expression',['../classgd_1_1_expression.html',1,'gd::Expression'],['../classgd_1_1_expression.html#a452b8034236a32b1dd4af0a7e1aeacc1',1,'gd::Expression::Expression()'],['../classgd_1_1_expression.html#ac14178ef483cc32bcca0f840b1bab31b',1,'gd::Expression::Expression(gd::String plainString_)'],['../classgd_1_1_expression.html#aa1ff91b3bdec0fc256901440c9f24bd2',1,'gd::Expression::Expression(const char *plainString_)']]],
  ['expressioncodegenerationinformation',['ExpressionCodeGenerationInformation',['../classgd_1_1_expression_code_generation_information.html',1,'gd']]],
  ['expressioncodegenerator',['ExpressionCodeGenerator',['../classgd_1_1_expression_code_generator.html',1,'gd']]],
  ['expressioncompletiondescription',['ExpressionCompletionDescription',['../structgd_1_1_expression_completion_description.html',1,'gd::ExpressionCompletionDescription'],['../structgd_1_1_expression_completion_description.html#a21276e4324266de3be10a819fecfcd92',1,'gd::ExpressionCompletionDescription::ExpressionCompletionDescription()']]],
  ['expressioncompletionfinder',['ExpressionCompletionFinder',['../classgd_1_1_expression_completion_finder.html',1,'gd']]],
  ['expressionfunctionrenamer',['ExpressionFunctionRenamer',['../classgd_1_1_expression_function_renamer.html',1,'gd']]],
  ['expressionmetadata',['ExpressionMetadata',['../classgd_1_1_expression_metadata.html',1,'gd::ExpressionMetadata'],['../classgd_1_1_expression_metadata.html#a59e81ac5a5f5b62311e89853aeb172f1',1,'gd::ExpressionMetadata::ExpressionMetadata(const gd::String &amp;returnType, const gd::String &amp;extensionNamespace, const gd::String &amp;name, const gd::String &amp;fullname, const gd::String &amp;description, const gd::String &amp;group, const gd::String &amp;smallicon)'],['../classgd_1_1_expression_metadata.html#a9e1c61f1965fbe6b6bf0965d051a8a4f',1,'gd::ExpressionMetadata::ExpressionMetadata()']]],
  ['expressionnode',['ExpressionNode',['../structgd_1_1_expression_node.html',1,'gd']]],
  ['expressionnodelocationfinder',['ExpressionNodeLocationFinder',['../classgd_1_1_expression_node_location_finder.html',1,'gd::ExpressionNodeLocationFinder'],['../classgd_1_1_expression_node_location_finder.html#a3e137f1b7143ed8768982be9e82dc489',1,'gd::ExpressionNodeLocationFinder::ExpressionNodeLocationFinder()']]],
  ['expressionobjectfinder',['ExpressionObjectFinder',['../classgd_1_1_expression_object_finder.html',1,'gd']]],
  ['expressionobjectrenamer',['ExpressionObjectRenamer',['../classgd_1_1_expression_object_renamer.html',1,'gd']]],
  ['expressionobjectsanalyzer',['ExpressionObjectsAnalyzer',['../classgd_1_1_expression_objects_analyzer.html',1,'gd']]],
  ['expressionparametermover',['ExpressionParameterMover',['../classgd_1_1_expression_parameter_mover.html',1,'gd']]],
  ['expressionparametersearcher',['ExpressionParameterSearcher',['../classgd_1_1_expression_parameter_searcher.html',1,'gd']]],
  ['expressionparser2',['ExpressionParser2',['../classgd_1_1_expression_parser2.html',1,'gd']]],
  ['expressionparser2nodeprinter',['ExpressionParser2NodePrinter',['../classgd_1_1_expression_parser2_node_printer.html',1,'gd']]],
  ['expressionparser2nodeworker',['ExpressionParser2NodeWorker',['../classgd_1_1_expression_parser2_node_worker.html',1,'gd']]],
  ['expressionparserdiagnostic',['ExpressionParserDiagnostic',['../structgd_1_1_expression_parser_diagnostic.html',1,'gd']]],
  ['expressionparsererror',['ExpressionParserError',['../structgd_1_1_expression_parser_error.html',1,'gd']]],
  ['expressionparserlocation',['ExpressionParserLocation',['../structgd_1_1_expression_parser_location.html',1,'gd']]],
  ['expressionsparametermover',['ExpressionsParameterMover',['../classgd_1_1_expressions_parameter_mover.html',1,'gd']]],
  ['expressionsrenamer',['ExpressionsRenamer',['../classgd_1_1_expressions_renamer.html',1,'gd']]],
  ['expressionvalidator',['ExpressionValidator',['../classgd_1_1_expression_validator.html',1,'gd']]],
  ['extensionandmetadata',['ExtensionAndMetadata',['../classgd_1_1_extension_and_metadata.html',1,'gd']]],
  ['extensionproperties',['ExtensionProperties',['../classgd_1_1_extension_properties.html',1,'gd']]],
  ['extensionsloader',['ExtensionsLoader',['../classgd_1_1_extensions_loader.html',1,'gd']]],
  ['extensionsloadingdone',['ExtensionsLoadingDone',['../classgd_1_1_extensions_loader.html#a4db9708d569962e706f82a44f9c3b930',1,'gd::ExtensionsLoader']]],
  ['externalevents',['ExternalEvents',['../classgd_1_1_external_events.html',1,'gd']]],
  ['externaleventscanbecompiledforascene',['ExternalEventsCanBeCompiledForAScene',['../class_dependencies_analyzer.html#af18794789ad871c78b02a44a5b43b2d1',1,'DependenciesAnalyzer']]],
  ['externaleventshasname',['ExternalEventsHasName',['../structgd_1_1_external_events_has_name.html',1,'gd']]],
  ['externallayout',['ExternalLayout',['../classgd_1_1_external_layout.html',1,'gd']]],
  ['externallayouthasname',['ExternalLayoutHasName',['../structgd_1_1_external_layout_has_name.html',1,'gd']]],
  ['externalsourcefilehasname',['ExternalSourceFileHasName',['../structgd_1_1_external_source_file_has_name.html',1,'gd']]],
  ['extrainformation',['ExtraInformation',['../classgd_1_1_instruction_metadata_1_1_extra_information.html',1,'gd::InstructionMetadata']]],
  ['events_20editor_20related_20classes',['Events Editor related classes',['../group___i_d_e_dialogs_events_editor.html',1,'']]]
];
